# Generated by Django 5.2.3 on 2025-06-13 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campeonato', models.CharField(max_length=30)),
                ('nombre_auspiciante', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CampeonatoEquipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campeonatoequipos', to='futbolec.campeonato')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoFutbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('siglas', models.CharField(max_length=5)),
                ('username_twitter', models.CharField(max_length=30)),
                ('campeonatos', models.ManyToManyField(through='futbolec.CampeonatoEquipos', to='futbolec.campeonato')),
            ],
        ),
        migrations.AddField(
            model_name='campeonatoequipos',
            name='equipo_futbol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campeonatoequipos', to='futbolec.equipofutbol'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='equipos',
            field=models.ManyToManyField(through='futbolec.CampeonatoEquipos', to='futbolec.equipofutbol'),
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('posicion_campo', models.CharField(max_length=30)),
                ('numero_camiseta', models.IntegerField()),
                ('sueldo', models.IntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='futbolec.equipofutbol')),
            ],
        ),
    ]
