# Generated by Django 3.2.4 on 2021-06-11 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrativo', '0005_auto_20210610_0545'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='modulos',
        ),
        migrations.AlterField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
